---
title: "Assignment 02"
output: html_document
date: '2022-10-06'
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

# Data Wrangling

## 1.

```{r}
chs_individual<-read.csv('chs_individual.csv')
chs_regional<-read.csv('chs_regional.csv')
dat<-chs_individual%>%left_join(chs_regional)
dat<-dat%>%group_by(male,hispanic)%>%
  mutate_at(vars(agepft:lat),function(x) {
    if (length(unique(x))>3) {
      x[is.na(x)]<-mean(x,na.rm=T)
    } else {
      x[is.na(x)]<-as.numeric(names(table(x))[table(x) == max(table(x))])
    }
    
    return(x)
  })%>%ungroup()
```

## 2.

```{r}
dat<-dat%>%
  mutate(obesity_level=cut(bmi,breaks=c(-Inf,14,22,24,+Inf),
                           labels=c('underweight','normal',
                                    'overweight','obese')))
# summary of BMI
summary(dat$bmi)

# table for counts of obesity_level
table(dat$obesity_level)
```

## 3.

```{r}
dat<-dat%>%mutate(smoke_gas_exposure=paste0('smoke=',smoke,'/gasstove=',gasstove))

table(dat$smoke_gas_exposure)
```

## 4.

```{r}
# Forced expiratory volume in 1 second (ml)
# town
dat%>%group_by(townname)%>%summarise(mean_fev=mean(fev),sd_fev=sd(fev))
# sex
dat%>%group_by(male)%>%summarise(mean_fev=mean(fev),sd_fev=sd(fev))
# obesity level
dat%>%group_by(obesity_level)%>%summarise(mean_fev=mean(fev),sd_fev=sd(fev))
# smoke_gas_exposure
dat%>%group_by(smoke_gas_exposure)%>%summarise(mean_fev=mean(fev),sd_fev=sd(fev))

# asthma
# town
dat%>%group_by(townname)%>%
  summarise(mean_asthma=mean(asthma),sd_asthma=sd(asthma))
# sex
dat%>%group_by(male)%>%
  summarise(mean_asthma=mean(asthma),sd_asthma=sd(asthma))
# obesity level
dat%>%group_by(obesity_level)%>%
  summarise(mean_asthma=mean(asthma),sd_asthma=sd(asthma))
# smoke_gas_exposure
dat%>%group_by(smoke_gas_exposure)%>%
  summarise(mean_asthma=mean(asthma),sd_asthma=sd(asthma))
```

# Looking at the Data (EDA)

## 1.

```{r}
dat%>%ggplot(aes(x=bmi,y=fev))+
  geom_point()+
  geom_smooth(method='lm')+
  facet_wrap(vars(townname))
```

## 2.

```{r}
dat%>%ggplot(aes(fev,fill=obesity_level))+
  geom_histogram()+
  scale_fill_manual(values=topo.colors(4))

dat%>%ggplot(aes(fev,fill=smoke_gas_exposure))+
  geom_histogram()+
  scale_fill_manual(values=rainbow(4))
```

## 3.

```{r}
dat%>%group_by(smoke_gas_exposure)%>%summarise(bmi=mean(bmi))%>%
  ggplot(aes(x=smoke_gas_exposure,y=bmi))+
  geom_bar(stat='identity')+
  theme(axis.text.x = element_text(angle=10))
```

## 4.

```{r}
dat%>%ggplot(aes(x=bmi,y=fev))+geom_point()+geom_smooth(method='lm')+
  geom_text(aes(y=1250,x=35),
            label=paste0('Correlation=',round(cor(dat$bmi,dat$fev),2)))

dat%>%ggplot(aes(x=smoke_gas_exposure,y=fev))+geom_boxplot()+
  theme(axis.text.x = element_text(angle=10))
```

## 5.

```{r}
library(leaflet)
dat2<-dat%>%group_by(townname)%>%
  summarise(lon=mean(lon),lat=mean(lat),pm25_mass=mean(pm25_mass))
leaflet(data=dat2)%>%
  addTiles()%>%
  addCircleMarkers(~lon, ~lat,radius = dat2$pm25_mass)
```

## 6.

```{r}
dat%>%ggplot(aes(x=fev,y=pm25_mass))+
  geom_point()+geom_smooth(method = 'lm')+
  geom_text(aes(x=2500,y=17),
            label=paste0('Correlation=',round(cor(dat$pm25_mass,dat$fev),2)))
```