---
title: "lab9"
author: "Eleanor Bi"
date: "12/13/2022"
output: html_document
---
(Rscript --vanilla -e 'rmarkdown::render("README.Rmd", output_format= "all")')
## Problem 2.
1. Create a n x k matrix of Poisson variables with mean lambda
```{r}
set.seed(1235)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}
f1=fun1(100,4)
mean(f1)
f1=fun1(1000,4)
#f1=fun1(10000,4)
#f1=fun1(50000,4) #longer time
fun1alt <- function(n = 100, k = 4, lambda = 4) {
  x= matrix( rpois(n*k, lambda) , ncol=4)  
  return(x)
}
# Benchmarking
library(microbenchmark)
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)
```
```{r}
d= matrix(1:16, ncol=4)
d
```
```{r}
diag(d)
d[2]
d[2,1]
d[c(1,6,11,16)]
```
## Problem 3.
Find the column max (hint: Checkout the function max.col()).
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12,), ncol=4)
M
# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
  x
}
fun2(M)
fun2alt <- function(x) {
  idx= max.col(t(x))
  x[cbind(idx, 1:4)]
}
fun2alt(M)
x <- matrix(rnorm(1e4), nrow=10)
# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)
```
## Problem 4. Show example

```{r}
library(parallel)
my_boot <- function(dat, stat, R, ncpus = 1L) {
  
  # Getting the random indices
  n <- nrow(dat)
  idx <- matrix(sample.int(n, n*R, TRUE), nrow=n, ncol=R)
 
  # Making the cluster using `ncpus`
  # STEP 1: GOES HERE
  cl <- makePSOCKcluster(4)    
  # STEP 2: GOES HERE
  clusterSetRNGStream(cl, 123)
  clusterExport(cl, c("stat", "dat","idx"), envir = environment())
  
    # STEP 3: THIS FUNCTION NEEDS TO BE REPLACES WITH parLapply
  ans <- lapply(seq_len(R), function(i) {
    stat(dat[idx[,i], , drop=FALSE])
  })
  
  # Coercing the list into a matrix
  ans <- do.call(rbind, ans)
  
  # STEP 4: GOES HERE
  ans
  
}
```

```{r}
# Bootstrap of an OLS
my_stat <- function(d) coef(lm(y ~ x, data=d))
# DATA SIM
set.seed(1)
n <- 500; R <- 1e4
x <- cbind(rnorm(n)); y <- x*5 + rnorm(n)
# Checking if we get something similar as lm
ans0 <- confint(lm(y~x))
ans1 <- my_boot(dat = data.frame(x, y), my_stat, R = R, ncpus = 2L)
# You should get something like this
t(apply(ans1, 2, quantile, c(.025,.975)))
##                   2.5%      97.5%
## (Intercept) -0.1372435 0.05074397
## x            4.8680977 5.04539763
ans0
##                  2.5 %     97.5 %
## (Intercept) -0.1379033 0.04797344
## x            4.8650100 5.04883353
```